language: node_js
node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

script: yarn run build

after_success:
  - yarn run test:cov
  - npm install coveralls@3.1.0 && yarn run nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls