language: node_js
node_js: stable

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

script: yarn run build

after_success:
  - npm install coveralls@3.1.0 nyc@15.0.0-beta.3
  - yarn run test:cov
  - npm run cov_report